### ISSUE TITLE
V5.0.0 Updates

### ISSUE THREAD

**Issue by nwarlen** [CascadeEnergy/consul-client#12]
v5.0.0 includes support for semver but there a few tweaks that should be made before it is ready for use:
- [ ] Include all tags in version search rather than just the first
- [ ] Ignore services with empty tags
- [ ] General Error Handling improvements

**Comment by cberube** [comment]
We are unlike to ever circle back to this issue. We'll almost certainly replace Consul with a different approach before we tackle these specific items.
